import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import configurationHandler from "./bold-commerce-api/cors-configuration";
import webhooksConfigurationHandler from "./bold-commerce-api/webhook-configuration";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await configurationHandler();
  await webhooksConfigurationHandler();
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
